PATH_H1B = 'data\H-1B_'
PATH_PWD = 'data\PWD_'
PATH_PERM = 'data\PERM_'
EXT_ORI = '.xlsx'
EXT_TO = '.csv'

STATES = ["AK","AL","AR","AZ","CA","CO","CT","DC","DE","FL","GA","GU","HI","IA","ID", "IL","IN","KS","KY","LA","MA","MD","ME","MH","MI","MN","MO","MP","MS","MT","NC","ND","NE","NH","NJ","NM","NV","NY", "OH","OK","OR","PA","PR","PW","RI","SC","SD","TN","TX","UT","VA","VI","VT","WA","WI","WV","WY"]
STATES_FULL = ["ALASKA","ALABAMA","ARKANSAS","ARIZONA","CALIFORNIA","COLORADO","CONNECTICUT","DISTRICT OF COLUMBIA","DELAWARE","FLORIDA",
               "GEORGIA","GUAM","HAWAII","IOWA","IDAHO", "ILLINOIS","INDIANA","KANSAS","KENTUCKY","LOUISIANA","MASSACHUSETTS","MARYLAND",
               "MAINE","MARSHALL ISLANDS","MICHIGAN","MINNESOTA","MISSOURI", "NORTHERN MARIANA ISLANDS","MISSISSIPPI","MONTANA","NORTH CAROLINA","NORTH DAKOTA","NEBRASKA",
               "NEW HAMPSHIRE","NEW JERSEY","NEW MEXICO","NEVADA","NEW YORK", "OHIO","OKLAHOMA","OREGON","PENNSYLVANIA","PUERTO RICO",
               "PALAU","RHODE ISLAND","SOUTH CAROLINA","SOUTH DAKOTA","TENNESSEE","TEXAS","UTAH","VIRGINIA","VIRGIN ISLANDS","VERMONT",
               "WASHINGTON","WISCONSIN","WEST VIRGINIA","WYOMING"]

STATUS_H1B = ['CERTIFIED', 'CERTIFIED-WITHDRAWN', 'DENIED', 'WITHDRAWN', 'REJECTED']
STATUS_PWD = ['DETERMINATION ISSUED', 'REDETERMINATION REVIEW - AFFIRMED',
       'REDETERMINATION REVIEW-OVERTURNED - MODIFIED',
       'CENTER DIRECTOR REVIEW - MODIFIED DETERMINATION',
       'CENTER DIRECTOR REVIEW - AFFIRMED DETERMINATION']
STATUS_PERM = ['Certified', 'Certified-Expired', 'Denied', 'Withdrawn']
EDUCATION = ['Doctorate (PhD)', "Master's", "Bachelor's", "Associate's", 'High School/GED',
             'Other Degree (JD, MD, etc.)', 'None']

OCCUPATION = {
    11: "Management",
    13: "Business and Finacial Operations",
    15: "Computer and Mathematical",
    17: "Architecture and Engineering",
    19: "Life, Physical, and Social Science Occupation",
    21: "Community and Social Service",
    23: "Legal",
    25: "Education, Training, and Library",
    27: "Arts, Design, Entertainment, Sports, and Media",
    29: "Healthcare Practitioners and Technical",
    31: "Healthcare Support",
    33: "Protective Service",
    35: "Food Preparation and Serving Related",
    37: "Building and Grounds Cleaning and Maintenance",
    39: "Personal Care and Service",
    41: "Sales and Related",
    43: "Office and Administrative Support",
    45: "Farming, Fishing, and Forestry",
    47: "Construction and Extration",
    49: "Installation, Maintenance, and Repair",
    51: "Production",
    53: "Transportation and Material Moving"}

YEARS = [2014, 2015, 2016, 2017, 2018]

NUM_COLUMN_H1B = 11

COLUMNS_H1B = [
    'STATUS',
    'VISA',
    'EMPLOYER',
    'CITY',
    'STATE',
    'TOTAL',
    'SOC_CODE',
    'SOC_NAME',
    'JOB_TITLE',
    'WAGE',
    'WAGE_UNIT',
    'PW',
    'PW_UNIT']

COLUMNS_PWD = [
    'STATUS',
    'VISA',
    'EMPLOYER',
    'CITY',
    'STATE',
    'NAICS_CODE',
    'SOC_CODE',
    'SOC_NAME',
    'JOB_TITLE',
    'EDUCATION',
    'WAGE',
    'WAGE_UNIT']

COLUMNS_PERM = [
    'STATUS',
    'VISA',
    'EMPLOYER',
    'CITY',
    'STATE',
    'NAICS_CODE',
    'INDUSTRY',
    'SOC_CODE',
    'SOC_NAME',
    'JOB_TITLE',
    'WAGE',
    'WAGE_UNIT',
    'CITIZENSHIP']

# for index, row in df.iterrows():
UNITS = ['Year', 'Month', 'Bi-Weekly', 'Week', 'Hour']
FACTORS_UNITS = [1, 12, 27, 54, 2160]

COLUMNS_YEAR_H1B = [
    # 2014
    ['STATUS',
    'VISA_CLASS',
    'LCA_CASE_EMPLOYER_NAME',
    'LCA_CASE_EMPLOYER_CITY',
    'LCA_CASE_EMPLOYER_STATE',
    'TOTAL_WORKERS',
    'LCA_CASE_SOC_CODE',
    'LCA_CASE_SOC_NAME',
    'LCA_CASE_JOB_TITLE',
    'LCA_CASE_WAGE_RATE_FROM',
    'LCA_CASE_WAGE_RATE_UNIT',
    'PW_1',
    'PW_UNIT_1'],
    # 2015
    ['CASE_STATUS',
    'VISA_CLASS',
    'EMPLOYER_NAME',
    'EMPLOYER_CITY',
    'EMPLOYER_STATE',
    'TOTAL WORKERS',
    'SOC_CODE',
    'SOC_NAME',
    'JOB_TITLE',
    'WAGE_RATE_OF_PAY',
    'WAGE_UNIT_OF_PAY',
    'PREVAILING_WAGE',
    'PW_UNIT_OF_PAY'],
    # 2016
    ['CASE_STATUS',
    'VISA_CLASS',
    'EMPLOYER_NAME',
    'EMPLOYER_CITY',
    'EMPLOYER_STATE',
    'TOTAL_WORKERS',
    'SOC_CODE',
    'SOC_NAME',
    'JOB_TITLE',
    'WAGE_RATE_OF_PAY_FROM',
    'WAGE_UNIT_OF_PAY',
    'PREVAILING_WAGE',
    'PW_UNIT_OF_PAY'],
    # 2017
    ['CASE_STATUS',
     'VISA_CLASS',
    'EMPLOYER_NAME',
    'EMPLOYER_CITY',
    'EMPLOYER_STATE',
    'TOTAL_WORKERS',
    'SOC_CODE',
    'SOC_NAME',
    'JOB_TITLE',
    'WAGE_RATE_OF_PAY_FROM',
    'WAGE_UNIT_OF_PAY',
    'PREVAILING_WAGE',
    'PW_UNIT_OF_PAY'],
    # 2018
    ['CASE_STATUS',
     'VISA_CLASS',
    'EMPLOYER_NAME',
    'EMPLOYER_CITY',
    'EMPLOYER_STATE',
    'TOTAL_WORKERS',
    'SOC_CODE',
    'SOC_NAME',
    'JOB_TITLE',
    'WAGE_RATE_OF_PAY_FROM',
    'WAGE_UNIT_OF_PAY',
    'PREVAILING_WAGE',
    'PW_UNIT_OF_PAY']
]

COLUMNS_YEAR_PWD = [
    # 2014
    ['CASE_STATUS',
     'VISA_CLASS',
     'EMPLOYER_LEGAL_BUSINESS_NAME',
     'EMPLOYER CITY',
     'EMPLOYER STATE',
     'NAICS_US_CODE',
     'PWD_SOC_CODE',
     'PWD_SOC_TITLE',
     'PW_JOB_TITLE',
     'PRIMARY_EDUCATION_LEVEL',
     'PWD_WAGE_RATE',
     'PWD_UNIT_OF_PAY'],
    # 2015
    ['STATUS',
     'VISA_CLASS',
     'BUSINESS_NAME',
     'EMPLOYER CITY',
     'EMPLOYER STATE',
     'NAIC_ID',
     'SOC_CODE',
     'SOC_CODE_NAME',
     'JOB_TITLE',
     'EDUCATION_LEVEL',
     'PREVAIL_WAGE',
     'PAY_RANGE_DESC'],
    # 2016
    ['CASE_STATUS',
    'VISA_CLASS',
    'BUSINESS_NAME',
    'EMPLOYER_CITY',
    'EMPLOYER_STATE',
    'NAICS_CODE',
    'PWD_SOC_CODE',
    'PWD_SOC_TITLE',
    'JOB_TITLE',
    'PRIMARY_EDUCATION_LEVEL',
    'PWD_WAGE_RATE',
    'PWD_UNIT_OF_PAY'],
    # 2017
    ['CASE_STATUS',
     'VISA_CLASS',
     'BUSINESS_NAME',
     'EMPLOYER_CITY',
     'EMPLOYER_STATE',
     'NAICS_CODE',
     'PWD_SOC_CODE',
     'PWD_SOC_TITLE',
     'JOB_TITLE',
     'PRIMARY_EDUCATION_LEVEL',
     'PWD_WAGE_RATE',
     'PWD_UNIT_OF_PAY'],
    # 2018
    ['CASE_STATUS',
     'VISA_CLASS',
     'BUSINESS_NAME',
     'EMPLOYER _CITY',
     'EMPLOYER _STATE',
     'NAICS_CODE',
     'PWD_SOC_CODE',
     'PWD_SOC_TITLE',
     'JOB_TITLE',
     'PRIMARY_EDUCATION_LEVEL',
     'PWD_WAGE_RATE',
     'PWD_UNIT_OF_PAY']
]

COLUMNS_YEAR_PERM = [
    # 2014
    ['Case_Status',
     'Class_of_Admission',
     'Employer_Name',
     'Employer_City',
     'Employer_State',
     '2007_NAICS_US_CODE',
     '2007_NAICS_US_TITLE',
     'PW_SOC_Code',
     'PW_SOC_TITLE',
     'PW_Job_Title_9089',
     'WAGE_OFFERED_FROM_9089',
     'WAGE_OFFERED_UNIT_OF_PAY_9089',
     'Country_of_Citizenship'],
    # 2015
    ['CASE_STATUS',
     'CLASS_OF_ADMISSION',
     'EMPLOYER_NAME',
     'EMPLOYER_CITY',
     'EMPLOYER_STATE',
     'NAICS_US_CODE',
     'NAICS_US_TITLE',
     'PW_SOC_CODE',
     'PW_SOC_TITLE',
     'PW_Job_Title_9089',
     'WAGE_OFFER_FROM_9089',
     'WAGE_OFFER_UNIT_OF_PAY_9089',
     'COUNTRY_OF_CITIZENSHIP'],
    # 2016
    ['CASE_STATUS',
     'CLASS_OF_ADMISSION',
     'EMPLOYER_NAME',
     'EMPLOYER_CITY',
     'EMPLOYER_STATE',
     'NAICS_US_CODE',
     'NAICS_US_TITLE',
     'PW_SOC_CODE',
     'PW_SOC_TITLE',
     'JOB_INFO_JOB_TITLE',
     'WAGE_OFFER_FROM_9089',
     'WAGE_OFFER_UNIT_OF_PAY_9089',
     'COUNTRY_OF_CITIZENSHIP'],
    # 2017
    ['CASE_STATUS',
     'CLASS_OF_ADMISSION',
     'EMPLOYER_NAME',
     'EMPLOYER_CITY',
     'EMPLOYER_STATE',
     'NAICS_US_CODE',
     'NAICS_US_TITLE',
     'PW_SOC_CODE',
     'PW_SOC_TITLE',
     'JOB_INFO_JOB_TITLE',
     'WAGE_OFFER_FROM_9089',
     'WAGE_OFFER_UNIT_OF_PAY_9089',
     'COUNTRY_OF_CITIZENSHIP'],
    # 2018
    ['CASE_STATUS',
     'CLASS_OF_ADMISSION',
     'EMPLOYER_NAME',
     'EMPLOYER_CITY',
     'EMPLOYER_STATE',
     'NAICS_US_CODE',
     'NAICS_US_TITLE',
     'PW_SOC_CODE',
     'PW_SOC_TITLE',
     'JOB_INFO_JOB_TITLE',
     'WAGE_OFFER_FROM_9089',
     'WAGE_OFFER_UNIT_OF_PAY_9089',
     'COUNTRY_OF_CITIZENSHIP']
]